---
title: "annotate_manifest"
author: "Levi Waldron"
date: "September 5, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

# Annotate the GDC manifest

```{r, cache=FALSE}
##BiocInstaller::biocLite("waldronlab/BiocInterfaces")
library(BiocInterfaces)
library(jsonlite)
library(curl)
library(downloader)
```

```{r, cache=FALSE}
base.dir = "/home/lwaldron/git/ovc_purecn"
gdc.manifest.file = "gdc_manifest.2016-09-06T01-07-32.436960.tsv"
bed.dir = file.path(base.dir, "data")
output.dir = file.path(base.dir, "output")
manifest = read.delim(file.path(bed.dir, gdc.manifest.file), as.is=TRUE)
```

```{r}
manifest$barcode = BiocInterfaces::TCGAtranslateID(manifest$id)
manifest = cbind(manifest, BiocInterfaces::TCGAbiospec(manifest$barcode))
```
```{r curl}
res = lapply(manifest$id, function(uuid){
  print(uuid)
  con = curl::curl(paste0("https://gdc-api.nci.nih.gov/files/", uuid, "?pretty=true&fields=analysis.metadata.read_groups.target_capture_kit_target_region,analysis.metadata.read_groups.target_capture_kit_name,analysis.metadata.read_groups.target_capture_kit_vendor,analysis.metadata.read_groups.target_capture_kit_catalog_number"))
  x = jsonlite::fromJSON(con)
  return(x)
})
```

Motivation for substitution: https://earray.chem.agilent.com/suredesign/static/SureDesign_3.5.2_Release_Notes.pdf

```{r}
y=lapply(res, function(x) unique(x$data$analysis$metadata$read_groups))
y = do.call(rbind, y)
manifest = cbind(manifest, y)
manifest$target_capture_kit_catalog_number = sub("S02972011", "S07604514",
                                manifest$target_capture_kit_catalog_number)
```

Choose a bedfile for each, just the first one listed. Also, use "SeqCap_EZ_Exome_v3_capture.bed" for the Agilent "https://earray.chem.agilent.com/earray/".

```{r}
bedfiles = strsplit(manifest$target_capture_kit_target_region, split="|", fixed=TRUE)
for (i in 1:length(bedfiles)){
  for (j in 1:length(bedfiles[[i]])){
    if(identical(bedfiles[[i]][[j]], "https://earray.chem.agilent.com/earray/")){
      bedfiles[[i]][[j]] <- "SeqCap_EZ_Exome_v3_capture.bed"
    }else{
      bedfiles[[i]][[j]] <- sub(".+/", "", bedfiles[[i]][[j]])
    }
    if(!file.exists(file.path(bed.dir, bedfiles[[i]][[j]])))
      bedfiles[[i]][[j]] <- NA
  }
}
manifest$bedfiles <- sapply(bedfiles, function(x) na.omit(x)[1])
```

```{r, cache=FALSE}
write.table(manifest, file=file.path(output.dir, "ovc_manifest.tsv"), sep="\t")
```

# Download capture regions
```{r}
urls = strsplit(manifest$target_capture_kit_target_region, split="|", fixed=TRUE)
urls = unique(do.call(c, urls))
urls = urls[!is.na(urls)]
urls = urls[!grepl("/$", urls)] #don't bother with those ending in "/"
urls = sub("ftp", "http", urls)
fnames = sapply(strsplit(urls, "/"), function(x) x[length(x)])
fnames = file.path(bed.dir, fnames)
```

```{r, cache=FALSE}
for (i in 1:length(urls)){
  print(c(i, urls[i]))
  if(!file.exists(fnames[i])){
    try(downloader::download(urls[i], destfile=fnames[i]))
  }
}
```

